name: vloo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter:
    sdk: flutter


  #loaders
  flutter_spinkit: ^5.2.0

  #building form in flutter
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0

  #loader
  bot_toast: ^4.0.3

  #video player
  video_player: ^2.7.1

  #resize widget
  flutter_box_transform: ^0.4.2
  matrix_gesture_detector_pro: ^1.0.0

  vector_math: ^2.1.0

  # language localization
  easy_localization: ^3.0.3

  # toggle switch
  toggle_switch: ^2.1.0

  #SVG
  flutter_svg: ^2.0.9

  #GIG
  #flutter_gif:

  #googlefonts
  google_fonts: ^6.1.0

  #internet connectivity checker
  #connectivity_plus: ^5.0.2

  #animation text 
  animated_text_kit: ^4.2.2

  #verification code input
  pinput: ^3.0.1

  #country code picker
  fl_country_code_picker: ^0.1.7+1

  #text color picker
  flutter_colorpicker: ^1.0.3

  #video recorder
  screen_recorder: ^0.2.0

  #gallery picker
  #photo_manager:
  neon_widgets: ^2.0.0

  #HTTP Requests
  dio: ^5.3.2
  #HTTP Requests
  http: ^1.1.0

  #shared storage
  get_storage: ^2.1.1

  auto_size_text_field: ^2.2.3

  #pull to refresh data in list
  pull_to_refresh: ^2.0.0

  #  #list sorting reordering
  #  drag_and_drop_lists: ^0.2.1
  #drag_and_drop_lists: ^0.3.3
  #kanban_board: ^0.1.0
 # flutter_draggable_list: ^1.0.2
  flutter_draggable_gridview: ^0.0.9

  #url opener
  url_launcher: ^6.1.14

  #path provider
  #path_provider: ^2.0.15
  path_provider: ^2.1.3

  #qr_code_scanner
  qr_code_scanner: ^1.0.1

  blur: ^3.1.0
  image_picker: ^1.0.4
  image: ^3.0.1
  remove_background: ^0.0.1
  image_gallery_saver: ^2.0.3
  flutter_stripe: ^10.0.0
  widget_and_text_animator: ^1.1.5
  glitcheffect: ^1.1.1
  text_neon_widget: ^1.0.6
  fade_out_particle: ^1.2.1
  cutout_text_effect: ^0.0.1
  animation_wrappers: ^3.0.0
  animate_do: ^3.1.2
  cached_network_image: ^3.3.0
  animated_flutter_widgets: ^0.0.2
  # Add the flutter_localizations package
  flutter_localizations:
    sdk: flutter
  # Add the intl package
  intl: any

  #flutter icons
  flutter_launcher_icons: ^0.10.0
  country_codes: ^2.2.0
  spring: ^2.0.2
  flutter_slidable: ^3.1.0
  hive: ^2.2.3
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"



dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true #for localizations
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
#    - assets/translations/

  fonts:
    - family: FlutterCustomIcons
      fonts:
        - asset: assets/fonts/FlutterCustomIcons.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/FlutterCustomIcons.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
          weight: 700
    - family: ChalkDuster
      fonts:
        - asset: assets/fonts/Chalkduster.ttf
          weight: 700
    - family: chantal
      fonts:
        - asset: assets/fonts/chantal_medium.ttf
          weight: 700
    - family: CocogooseTrial
      fonts:
        - asset: assets/fonts/Cocogoose_trial.otf
          weight: 700
    - family: DSMoster
      fonts:
        - asset: assets/fonts/DSMoster.ttf
          weight: 700
    - family: EBGaramond08
      fonts:
        - asset: assets/fonts/EBGaramond08-Regular.ttf
          weight: 700
    - family: edosz
      fonts:
        - asset: assets/fonts/edosz.ttf
          weight: 700
    - family: Gagalin
      fonts:
        - asset: assets/fonts/Gagalin-Regular.ttf
          weight: 700
    - family: KOMIKAX
      fonts:
        - asset: assets/fonts/KOMIKAX_.ttf
          weight: 700
    - family: NocturneSerif
      fonts:
        - asset: assets/fonts/NocturneSerif-Regular.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: PoiretOne
      fonts:
        - asset: assets/fonts/PoiretOne-Regular.ttf
          weight: 700
    - family: RifficFree
      fonts:
        - asset: assets/fonts/RifficFree-Bold.ttf
          weight: 700
    - family: UTLaurelle
      fonts:
        - asset: assets/fonts/UTLaurelle-Regular.ttf
          weight: 700
